### ISSUE TITLE
Checklist to ship the OKD bits

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3271]
We created the OKD bundles and did a basic testing but still we are not able to release the crc with OKD. We don't want to confuse user if we ship one `crc` binary with OCP and one with OKD. During the internal discussion @cfergeau suggested better to use preset issue https://github.com/code-ready/crc/issues/3101 and have it implemented. This issue just a checklist what all we have to do to make it happen.

- [x] OKD preset https://github.com/code-ready/crc/issues/3101
- [ ] Document update around OKD preset
- [x] Internal CI job to create OKD bundle

**Comment by praveenkumar** [comment]
https://crc.dev/blog/posts/2022-08-22-okd-on-crc/ is already published how to use crc with okd. we need to update some parts of our doc, https://crc.dev/crc/#minimum-system-requirements_gsg for example

**Comment by rohanKanojia** [comment]
hello, What task is pending to close this issue. I see after reading https://github.com/crc-org/crc/issues/3271#issuecomment-1265235599 documentation effort is also complete, right?

**Comment by praveenkumar** [comment]
Yes, closing this one.
