### ISSUE TITLE
Podman desktop related Installer issues

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3428]
Installer issues:
  * [ ] [Configurable Podman install location on Mac](https://github.com/containers/podman-desktop/issues/810)

Desktop issues:
  * [x] [Podman installation not readable](https://github.com/containers/podman-desktop/issues/809)
  * [x] [[0.9.1] Windows 10 WSL2 installation not detected](https://github.com/containers/podman-desktop/issues/857)
  * [x] [Installation of folder does not work on Windows with home folder containing spaces](https://github.com/containers/podman-desktop/issues/806)

**Comment by anjannath** [comment]
the upstream issues are resolved and closed
